--BEGIN TRANSACTION;
INSERT INTO v_settings (numbering_plan, event_socket_ip_address, event_socket_port, event_socket_password, xml_rpc_http_port, xml_rpc_auth_realm, xml_rpc_auth_user, xml_rpc_auth_pass, admin_pin, smtp_host, smtp_secure, smtp_auth, smtp_username, smtp_password, smtp_from, smtp_from_name, mod_shout_decoder, mod_shout_volume) VALUES ('US','127.0.0.1',8021,'ClueCon',8787,'localhost','xmlrpc','7e4d3i',1234,'','none','','','','','Voicemail','i386',0.3);
INSERT INTO v_vars VALUES(1,1,'sound_prefix','$${base_dir}/sounds/en/us/callie','Sound','true',3,'U2V0cyB0aGUgc291bmQgZGlyZWN0b3J5Lg==');
INSERT INTO v_vars VALUES(1,2,'domain','$${local_ip_v4}','Domain','true',1,'U2V0cyB0aGUgZGVmYXVsdCBkb21haW4u');
INSERT INTO v_vars VALUES(1,3,'domain_name','$${domain}','Domain','true',2,'');
INSERT INTO v_vars VALUES(1,4,'hold_music','local_stream://moh','Music on Hold','true',4,'');
INSERT INTO v_vars VALUES(1,5,'global_codec_prefs','G7221@32000h,G7221@16000h,G722,PCMU,PCMA,GSM','Codecs','true',5,'RzcyMjFAMzIwMDBoLEc3MjIxQDE2MDAwaCxHNzIyLFBDTVUsUENNQSxpTEJDLEdTTSxIMjYzLEgyNjQ=');
INSERT INTO v_vars VALUES(1,6,'outbound_codec_prefs','PCMU,PCMA,GSM','Codecs','true',6,'ZGVmYXVsdDogUENNVSxQQ01BLEdTTQ==');
INSERT INTO v_vars VALUES(1,7,'xmpp_client_profile','xmppc','Dingaling','true',7,'eG1wcF9jbGllbnRfcHJvZmlsZSBhbmQgeG1wcF9zZXJ2ZXJfcHJvZmlsZSB4bXBwX2NsaWVudF9wcm9maWxlIGNhbiBiZSBhbnkgc3RyaW5nLiB4bXBwX3NlcnZlcl9wcm9maWxlIGlzIGFwcGVuZGVkIHRvICJkaW5nYWxpbmdfIiB0byBmb3JtIHRoZSBkYXRhYmFzZSBuYW1lIGNvbnRhaW5pbmcgdGhlICJzdWJzY3JpcHRpb25zIiB0YWJsZS4gdXNlZCBieTogZGluZ2FsaW5nLmNvbmYueG1sIGVudW0uY29uZi54bWw=');
INSERT INTO v_vars VALUES(1,8,'xmpp_server_profile','xmpps','Dingaling','true',8,'');
INSERT INTO v_vars VALUES(1,9,'bind_server_ip','auto','Dingaling','true',9,'Q2FuIGJlIGFuIGlwIGFkZHJlc3MsIGEgZG5zIG5hbWUsIG9yICJhdXRvIi4gVGhpcyBkZXRlcm1pbmVzIGFuIGlwIGFkZHJlc3MgYXZhaWxhYmxlIG9uIHRoaXMgaG9zdCB0byBiaW5kLiBJZiB5b3UgYXJlIHNlcGFyYXRpbmcgUlRQIGFuZCBTSVAgdHJhZmZpYywgeW91IHdpbGwgd2FudCB0byBoYXZlIHVzZSBkaWZmZXJlbnQgYWRkcmVzc2VzIHdoZXJlIHRoaXMgdmFyaWFibGUgYXBwZWFycy4gVXNlZCBieTogZGluZ2FsaW5nLmNvbmYueG1s');
INSERT INTO v_vars VALUES(1,10,'external_rtp_ip','stun:stun.fwdnet.net','IP Address','true',10,'KElmIHlvdScncmUgZ29pbmcgdG8gbG9hZCB0ZXN0IHRoZW4gcGxlYXNlIGlucHV0IHJlYWwgSVAgYWRkcmVzc2VzIGZvciBleHRlcm5hbF9ydHBfaXAgYW5kIGV4dGVybmFsX3NpcF9pcCkNCg0KQ2FuIGJlIGFuIG9uZSBvZjoNCiAgIGlwIGFkZHJlc3M6ICIxMi4zNC41Ni43OCINCiAgIGEgc3R1biBzZXJ2ZXIgbG9va3VwOiAic3R1bjpzdHVuLnNlcnZlci5jb20iDQogICBhIEROUyBuYW1lOiAiaG9zdDpob3N0LnNlcnZlci5jb20iDQoNCndoZXJlIGZzLm15ZG9tYWluLmNvbSBpcyBhIEROUyBBIHJlY29yZC11c2VmdWwgd2hlbiBmcyBpcyBvbiBhIGR5bmFtaWMgSVAgYWRkcmVzcywgYW5kIHVzZXMgYSBkeW5hbWljIEROUyB1cGRhdGVyLiBJZiB1bnNwZWNpZmllZCwgdGhlIGJpbmRfc2VydmVyX2lwIHZhbHVlIGlzIHVzZWQuIFVzZWQgYnk6IHNvZmlhLmNvbmYueG1sIGRpbmdhbGluZy5jb25mLnhtbA==');
INSERT INTO v_vars VALUES(1,11,'external_sip_ip','stun:stun.fwdnet.net','IP Address','true',11,'VXNlZCBhcyB0aGUgcHVibGljIElQIGFkZHJlc3MgZm9yIFNEUC4NCg0KQ2FuIGJlIGFuIG9uZSBvZjoNCiAgIGlwIGFkZHJlc3M6ICIxMi4zNC41Ni43OCINCiAgIGEgc3R1biBzZXJ2ZXIgbG9va3VwOiAic3R1bjpzdHVuLnNlcnZlci5jb20iDQogICBhIEROUyBuYW1lOiAiaG9zdDpob3N0LnNlcnZlci5jb20iDQoNCndoZXJlIGZzLm15ZG9tYWluLmNvbSBpcyBhIEROUyBBIHJlY29yZC11c2VmdWwgd2hlbiBmcyBpcyBvbiBhIGR5bmFtaWMgSVAgYWRkcmVzcywgYW5kIHVzZXMgYSBkeW5hbWljIEROUyB1cGRhdGVyLiBJZiB1bnNwZWNpZmllZCwgdGhlIGJpbmRfc2VydmVyX2lwIHZhbHVlIGlzIHVzZWQuIFVzZWQgYnk6IHNvZmlhLmNvbmYueG1sIGRpbmdhbGluZy5jb25mLnhtbA==');
INSERT INTO v_vars VALUES(1,12,'unroll_loops','true','SIP','true',12,'VXNlZCB0byB0dXJuIG9uIHNpcCBsb29wYmFjayB1bnJvbGxpbmcu');
INSERT INTO v_vars VALUES(1,13,'call_debug','false','Defaults','true',13,'');
INSERT INTO v_vars VALUES(1,14,'console_loglevel','info','Defaults','true',14,'');
INSERT INTO v_vars VALUES(1,15,'default_areacode',208,'Defaults','true',15,'');
INSERT INTO v_vars VALUES(1,16,'uk-ring','%(400,200,400,450);%(400,2200,400,450)','Defaults','true',16,'');
INSERT INTO v_vars VALUES(1,17,'us-ring','%(2000, 4000, 440.0, 480.0)','Defaults','true',17,'');
INSERT INTO v_vars VALUES(1,18,'fr-ring','%(1500, 3500, 440.0, 0.0)','Defaults','true',18,'');
INSERT INTO v_vars VALUES(1,19,'rs-ring','%(1000, 4000, 425.0, 0.0)','Defaults','true',19,'');
INSERT INTO v_vars VALUES(1,20,'bong-ring','v=-7;%(100,0,941.0,1477.0);v=-7;>=2;+=.1;%(1400,0,350,440)','Defaults','true',20,'');
INSERT INTO v_vars VALUES(1,21,'sit','%(274,0,913.8);%(274,0,1370.6);%(380,0,1776.7)','Defaults','true',21,'');
INSERT INTO v_vars VALUES(1,22,'sip_tls_version','tlsv1','SIP and TLS','true',21,'U0lQIGFuZCBUTFMgc2V0dGluZ3Mu');
INSERT INTO v_vars VALUES(1,23,'internal_auth_calls','true','SIP Profile: Internal','true',22,'');
INSERT INTO v_vars VALUES(1,24,'internal_sip_port',5060,'SIP Profile: Internal','true',23,'');
INSERT INTO v_vars VALUES(1,25,'internal_tls_port',5061,'SIP Profile: Internal','true',24,'');
INSERT INTO v_vars VALUES(1,26,'internal_ssl_enable','false','SIP Profile: Internal','true',25,'');
INSERT INTO v_vars VALUES(1,27,'internal_ssl_dir','$${base_dir}/conf/ssl','SIP Profile: Internal','true',26,'');
INSERT INTO v_vars VALUES(1,28,'external_auth_calls','false','SIP Profile: External','true',27,'');
INSERT INTO v_vars VALUES(1,29,'external_sip_port',5080,'SIP Profile: External','true',28,'');
INSERT INTO v_vars VALUES(1,30,'external_tls_port',5081,'SIP Profile: External','true',29,'');
INSERT INTO v_vars VALUES(1,31,'external_ssl_enable','false','SIP Profile: External','true',29,'');
INSERT INTO v_vars VALUES(1,32,'external_ssl_dir','$${base_dir}/conf/ssl','SIP Profile: External','true',30,'');
INSERT INTO v_vars VALUES(1,33,'use_profile','internal','Defaults','true',31,'');
INSERT INTO v_vars VALUES(1,34,'default_language','en','Defaults','true',32,'');
INSERT INTO v_vars VALUES(1,35,'default_dialect','us','Defaults','true',33,'');
INSERT INTO v_vars VALUES(1,36,'default_voice','callie','Defaults','true',34,'');
SELECT setval('v_vars_var_uuid_seq', (SELECT MAX(var_uuid) FROM v_vars)+1);
CREATE INDEX index_billsec ON v_xml_cdr(billsec);
CREATE INDEX index_caller_id_name ON v_xml_cdr(caller_id_name);
CREATE INDEX index_destination_number ON v_xml_cdr(destination_number);
CREATE INDEX index_duration ON v_xml_cdr(duration);
CREATE INDEX index_hangup_cause ON v_xml_cdr(hangup_cause);
CREATE INDEX index_start_stamp ON v_xml_cdr(start_stamp);
--COMMIT;
