<?php
	//application details
		$apps[$x]['name'] = "Content Manager";
		$apps[$x]['guid'] = '892C8D0B-BFA5-1BDF-E090-A974DA7A7C5E';
		$apps[$x]['category'] = 'System';
		$apps[$x]['subcategory'] = '';
		$apps[$x]['version'] = '';
		$apps[$x]['license'] = 'Mozilla Public License 1.1';
		$apps[$x]['url'] = 'http://www.fusionpbx.com';
		$apps[$x]['description']['en'] = 'Manage Content for any page in the interface.';

	//menu details
		$apps[$x]['menu'][0]['title']['en'] = 'Content Manager';
		$apps[$x]['menu'][0]['guid'] = '90397352-395C-40F6-2087-887144ABC06D';
		$apps[$x]['menu'][0]['parent_guid'] = '02194288-6D56-6D3E-0B1A-D53A2BC10788';
		$apps[$x]['menu'][0]['category'] = 'internal';
		$apps[$x]['menu'][0]['path'] = '/mod/content/rsslist.php';
		$apps[$x]['menu'][0]['groups'][] = 'admin';
		$apps[$x]['menu'][0]['groups'][] = 'superadmin';

	//permission details
		$apps[$x]['permissions'][0]['name'] = 'content_view';
		$apps[$x]['permissions'][0]['groups'][] = 'admin';
		$apps[$x]['permissions'][0]['groups'][] = 'superadmin';

		$apps[$x]['permissions'][1]['name'] = 'content_add';
		$apps[$x]['permissions'][1]['groups'][] = 'admin';
		$apps[$x]['permissions'][1]['groups'][] = 'superadmin';

		$apps[$x]['permissions'][2]['name'] = 'content_edit';
		$apps[$x]['permissions'][2]['groups'][] = 'admin';
		$apps[$x]['permissions'][2]['groups'][] = 'superadmin';

		$apps[$x]['permissions'][3]['name'] = 'content_delete';
		$apps[$x]['permissions'][3]['groups'][] = 'admin';
		$apps[$x]['permissions'][3]['groups'][] = 'superadmin';

	//schema details
		$y = 0; //table array index
		$z = 0; //field array index
		$apps[$x]['db'][$y]['table'] = 'v_rss';
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_id';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'serial';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer PRIMARY KEY';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'v_id';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_language';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsslanguage';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_category';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsscategory';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_category';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssubcategory';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_title';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsstitle';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_link';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsslink';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_desc';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssdesc';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_img';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssimg';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'bytea';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'blob';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'blob';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_optional_1';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssoptional1';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_optional_2';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssoptional2';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_optional_3';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssoptional3';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_optional_4';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssoptional4';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_optional_5';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssoptional5';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_add_date';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssadddate';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_add_user';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssadduser';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_del_date';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssdeldate';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_del_user';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssdeluser';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_order';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssorder';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_content';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsscontent';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_group';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssgroup';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';

		$y = 1; //table array index
		$z = 0; //field array index
		$apps[$x]['db'][$y]['table'] = 'v_rss_sub';
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_id';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssubid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'serial';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer PRIMARY KEY';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'v_id';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_id';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssid';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_language';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssublanguage';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_title';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssubtitle';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_link';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssublink';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_desc';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssubdesc';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_optional_1';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssuboptional1';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_optional_2';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssuboptional2';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_optional_3';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssuboptional3';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_optional_4';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssuboptional4';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_optional_5';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssuboptional5';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_add_date';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssubadddate';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_add_user';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssubadduser';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_del_user';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssubdeluser';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_del_date';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssubdeldate';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_parent_id';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssubparentid';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';

		$y = 2; //table array index
		$z = 0; //field array index
		$apps[$x]['db'][$y]['table'] = 'v_rss_sub_category';
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_category_id';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssubcategoryid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'serial';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer PRIMARY KEY';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'v_id';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_category_language';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssubcategorylanguage';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_category';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsscategory';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_category';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssubcategory';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_category_desc';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rsssubcategorydesc';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_add_user';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssadduser';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = 'rss_sub_add_date';
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = 'rssadddate';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description'] = '';

?>